name: Run Script

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: compiled-js

      - name: Execute script
        run: npm run start
        env:
          BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
